### ISSUE TITLE
[?] General Question

### ISSUE THREAD

**Issue by J-Daniel-1** [Vexed01/Vex-Cogs#4]
For your Status cog, when adding a service to a channel and being prompted with the mode and webhook, when saying `yes` for the webhook, should the bot automatically create the webhook when the setup is complete or does it only create it when an issue is posted?

**Comment by Vexed01** [comment]
It is coded to make the webhook, if not already present, when a status update is sent. This is so that if the webhook is deleted it does not error. Whilst that behaviour may be considered unfavourable, the user did request the cog to post as a webhook.

From a user experience perspective, it certainly would make sense to make the webhook when registering the channel for updates.
